### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ygarr** [redcorelinux/redcore-desktop#2]
Section 'redcore-desktop' in repos.conf has name different from repository name 'redcore' set inside repository

**Comment by V3n3RiX** [comment]
That error shows up if : 
- you havent updated the system in a very long time (6 months)
- you used an old iso image to install the system, and you're trying to update it

Use a fresh ISO to install the system, or run vasile --binmode before attempting to update.

**Comment by alecuba16** [comment]
I'm getting the same error also.

the solution is just rename on  /etc/portage/repos.conf/layman.conf:

> [**redcore-desktop**]
priority = 50
location = /var/lib/layman/redcore-desktop
layman-type = git
auto-sync = No

To:

> [**redcore**]
priority = 50
location = /var/lib/layman/redcore-desktop
layman-type = git
auto-sync = No

**Comment by V3n3RiX** [comment]
The command I posted above : vasile --binmode, will fix the issue...So I'm closing the issue now!

**Comment by alecuba16** [comment]
Vasile command is not part of Gentoo Linux, is only available in Redcore linux.

My solution works for Gentoo Linux.
